### ISSUE TITLE
NO WOLFENSTEIN 3-D DATA FILES to be found!

### ISSUE THREAD

**Issue by lyons88** [mozzwald/wolf4sdl#1]
I built this on Arm under Ubuntu 12.10, on my Chromebook. Using:

#define UPLOAD and APOGEE_1_0

In the version.h file, and I extracted the shareware game to the same Dir as the wolf3d binary, however it still says it can't find the Data files?

I'm sure I used Shareware version 1.0,  also tried with version 1.2 and:

#define CARMACIZED and UPLOAD and APOGEE_1_2

Same result?

These are the files I have in the dir with the wolf3d binary:

AUDIOHED.WL1  GAMEMAPS.WL1  README.WL1   VGAGRAPH.WL1  VSWAP.WL1  WOLF3D.EXE
AUDIOT.WL1    MAPHEAD.WL1   VGADICT.WL1  VGAHEAD.WL1   wolf3d

and the top of my version.h:

#ifndef _VERSION_H_
#define _VERSION_H_

#ifndef VERSIONALREADYCHOSEN              // used for batch compiling

/* Defines used for different versions */

//#define SPEAR
//#define SPEARDEMO
//#define UPLOAD
//#define GOODTIMES
//#define CARMACIZED
//#define APOGEE_1_0
//#define APOGEE_1_1
//#define APOGEE_1_2
//#define UPLOAD and APOGEE_1_0
#define CARMACIZED and UPLOAD and APOGEE_1_2
 /*
   //Wolf3d Full v1.1 Apogee (with ReadThis)   - define CARMACIZED and APOGEE_1_1
    //Wolf3d Full v1.4 Apogee (with ReadThis)   - define CARMACIZED
    //Wolf3d Full v1.4 GT/ID/Activision         - define CARMACIZED and GOODTIMES
    //Wolf3d Shareware v1.0                     - define UPLOAD and APOGEE_1_0
   // Wolf3d Shareware v1.1                     - define CARMACIZED and UPLOAD and APOGEE_1_1
    //Wolf3d Shareware v1.2                     - define CARMACIZED and UPLOAD and APOGEE_1_2
   // Wolf3d Shareware v1.4                     - define CARMACIZED and UPLOAD
   //Spear of Destiny Full and Mission Disks   - define CARMACIZED and SPEAR
                                                (and GOODTIMES for no FormGen quiz)
    //Spear of Destiny Demo                     - define CARMACIZED and SPEAR and SPEARDEMO
*/

Any help you can offer?

**Comment by mckaygerhard** [comment]
hi, it cannot be parsed in compile time such -DCARMACIZED -DUPLOAD etrc etc event defined it explicit in the version file?

i currently packaging the wolf4sdl for venenux (debian based) based on ones already in network, i noted that nobody reports that problem until stop here, so now i ask if that can be defined at compile time ..

**Comment by mozzwald** [comment]
You can add the defines to the CFLAGS variable:
make CFLAGS+="-DCARMACIZED -DUPLOAD"

**Comment by mckaygerhard** [comment]
i already defined and works, but must run the binary from the data files place.. if i defined in id_ca.cpp the data dir can be work run the binary outside the data files? e.g. defined gdictname[] 
= "/usr/share/wolf3d/vgadict." ? (and some reserved gchar names in same files)

**Comment by mozzwald** [comment]
It looks like you would need to modify most of the "open(" calls in id_ca.cpp, but it should work.

**Comment by mckaygerhard** [comment]
can i made a pull request and u can commit , if a user defined at make level "make -DDATADIR="/path" "?

**Comment by mozzwald** [comment]
perhaps you could go further and add command line option like "--configdir" where you can set the path to data files when running the wolf4sdl binary? either way, I can test your pull request and commit.

**Comment by mckaygerhard** [comment]
so then i'll pull tomorrow .. let me code and test

**Comment by mckaygerhard** [comment]
well i'll tested and worked fine, see the pull request and merge it!

i noted that this are only able to load wolf3d 1.4 and no previouslly.. that's cause me lot of headhache to tests...

**Comment by mckaygerhard** [comment]
well this now must be closed.. but i noted that can improve the makefile to produce various binary for run various games with one shot make command..  also provide install property, but for now this are enought.. later i'll provide a manpage and more more later improve the makefile and patch some features such crosshair (i see in another place)

debian packages also i'll provide later

**Comment by mckaygerhard** [comment]
pull was incomplete, the data dir parameter does not shot the macro definition, i forget to added a verification that if user already redefined tha DATADIR make parameter then redefine the macro and add to cflags the nes definition.. i'll put this in  newer pull
