### ISSUE TITLE
version number? 1.7+svnXXX or 1.8?

### ISSUE THREAD

**Issue by mckaygerhard** [mozzwald/wolf4sdl#5]
i note this git repo its a copy from the SVN (and the url does not work)

but i cant determine now the version!, its 1.7? 1.7+gitXXXX? or 1.7+svn262? or 1.8rcX?

**Comment by mozzwald** [comment]
The original source is from www.chaos-software.de.vu which is no long working. I found this mirror (perhaps the new home?) http://homepage.o2mail.de/mkroll/downloads.html

It is `Wolf4SDL v1.7 ($Revision: 256 $)`
