### ISSUE TITLE
Compiled Binaries Not Working on Raspberry Pi

### ISSUE THREAD

**Issue by dudleydes** [mozzwald/wolf4sdl#7]
After the [latest changes](https://github.com/mckayemu/wolf4sdl/commit/51206d09225a5a1ecc8d2c7321ddf09a05858337) to the source code, I have been unable to compile a binary that works for the 1.4 shareware version of the game on the Raspberry Pi 1. I am using the RetroPie v3.0 beta2 image which is based on Raspbian.

I used the source code before the changes were made and the compiled binary works. Here is what I did.

I commented out #define GOODTIMES in version.h. I changed the PREFIX in Makefile to /opt/retropie/ports/wolf3d and installed the binary to that folder. I placed the game data in ~/RetroPie/roms/ports/wolf3d, then launched wolf3d from the front-end EmulationStation using the following shell script

```
#!/bin/bash 
pushd ~/RetroPie/roms/ports/wolf3d/ 
/opt/retropie/supplementary/runcommand/runcommand.sh 0 "/opt/retropie/ports/wolf3d/bin/wolf3d"
```

With the new code, I made the same changes as above. In addition, I changed the DATADIR in Makefile and version.h to ~/RetroPie/roms/ports/wolf3d/ but the compiled binary does not work. I get a NO WOLFENSTEIN 3-D DATA FILES to be found! error.

If it's the simplest solution, I could host the unmodified source code as a fork for the Raspberry Pi.

**Comment by mckaygerhard** [comment]
As a tip, data files must point where the data are with absolute path, the "~" are not valid in the raspbian due  i suspect due the "front-end EmulationStation" (a windose like tool).

Please enable debug build and run again but this time with complete path and not using "~" in the path.

**Comment by dudleydes** [comment]
I changed the paths in DATADIR to full paths and that's fixed it. Thanks.

**Comment by mckaygerhard** [comment]
.this are a proof that windose like artifacts always will have problems.
