### ISSUE TITLE
Feature Request: Don't block desktop/window manager on Ubuntu

### ISSUE THREAD

**Issue by tenleftfingers** [mozzwald/wolf4sdl#8]
Wolf4SDL v1.6 ($Revision: 232 $)
Ubuntu 16.04 64-bit

When wolf4sdl is running (and it's running very well), I cannot alt-tab to check emails etc. I have to quit the game completely.

Desired behaviour: ALT + Tab would cycle between other applications. Ctrl + arrow keys would allow me to switch desktops. I should be able to return to the game after doing any of these things.

**Comment by mozzwald** [comment]
Have you tried the [ubuntu maintained package](http://packages.ubuntu.com/xenial/wolf4sdl)?

**Comment by tenleftfingers** [comment]
It is the Ubuntu maintained package, yes.
wolf4sdl/xenial,now 1.7+svn262+dfsg1-3 amd64 [installed]

**Comment by mozzwald** [comment]
Have you tried ALT-ENTER to exit fullscreen mode?

**Comment by tenleftfingers** [comment]
Yes, it has no effect. It is interpreted the same as pressing Enter alone.

**Comment by mozzwald** [comment]
Maybe this will work for you http://www.jspenguin.org/software/sdlhack/

**Comment by tenleftfingers** [comment]
I've never heard of that before, nice idea. Thanks, but it doesn't work. Neither for wolf4sdl nor sdl-ball.

**Comment by mozzwald** [comment]
I got sdlhack to work with wolf4sdl by using: `sdlhack -k alt-z wolf3d`

Can you try that key combo?

**Comment by tenleftfingers** [comment]
I get "exec: wolf3d: not found" for that. But for: 
sdlhack -k alt-z wolf4sdl

the game runs, but still the shortcut is not recognised. Ubuntu 16.04 64-bit.

**Comment by mckaygerhard** [comment]
the path for binary games are not by default in path env, so maybe that has influence..

try this, made a symlink or better, move the wolf3d binary to /usr/bin and retry the sdlhack... and report feedback her!

**Comment by tenleftfingers** [comment]
Thanks. Just to be clear, are you asking me to move the .exe at /usr/share/games/wolf3d/wolf3d.exe to /usr/bin/ ?

**Comment by mckaygerhard** [comment]
exe ? that are u taking about? in linux does not exist exe files! i mean the binary executable.. maybe (i'm not test the sdlhack) the sdlhack search for the process and for the program in the path, and when not found, does not apply... or something!

**Comment by tenleftfingers** [comment]
The binary for this project is called wolf4sdl, not wolf3d. The .exe is just there because it got copied with the librarie that wolf4sdl requires.

I ran sudo ln -s /usr/games/wolf4sdl /usr/bin/wolf4sdl

But it made no difference. sdlhack -k alt-z wolf4sdl still does not allow me to exit the program with alt-z

**Comment by mckaygerhard** [comment]
umm i'm very confused, maybe the environment does not make it work, do u compile by yourself?

in any case this its a feature request, original game takes fullscreen and this as i understand only are the engine and emulates/runs all the original engine, the alt-enter are not part of original engine due was MSDOS, so maybe will not be made this required feature

so then sdlhack its u'r only chance, so try launch in background the game, then in same line while the game will lauch, follow in same console, the sdlhack command and see what happened

maybe: '/usr/games/wolf4sdl  & sdlhack -k alt-z wolf4sdl'

**Comment by tenleftfingers** [comment]
I can't get that to work either. Thanks anyway.

On Mon, Sep 5, 2016 at 3:15 PM, PICCORO Lenz McKAY <notifications@github.com

**Comment by mozzwald** [comment]
The [ubuntu package](http://packages.ubuntu.com/xenial/amd64/wolf4sdl/filelist) appears to use wold4sdl as the binary name so `sdlhack -k alt-z wolf4sdl` would be the correct usage in that case. I would suggest finding a key combo not used by the game that sdlhack can use. Also, you may have better luck finding someone in the ubuntu community who has a solution. The SDL/X/ALT-TAB/Fullscreen issue is common among SDL games.

Note: I did build this repo for my x86_64 laptop running Arch linux and I was able to get sdlhack to work with the ALT-Z combo. Perhaps you can try building this source on your ubuntu machine.

I'm not the original creator of the game port. This repo was created to be built for the [Zipit Z2](http://mozzwald.com/zipitz2) handheld computer (not running X). I updated the repo title to reflect this. Closing the issue as I won't be adding features unless they are specific or useful to the Zipit.

**Comment by tenleftfingers** [comment]
Thanks mozzwald, noted.

**Comment by mckaygerhard** [comment]
thanks for clarify mozzwald, i try with my own package in venenux repo that sdl hack and report feedback.. but its true, this repo its not for feature request that need too much work
